# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uz-Xx8dgf3wVQ4iI0RyaGRLqQQBwy_tX
"""

import torch
import pathlib
from torch.utils.data import Dataset
import numpy as np

class SliceData(Dataset):
  def __init__(self, root):
    # self.transform = transform
    self.examples = []
    files = list(pathlib.Path(root).iterdir())
    for fname in files:
      kspace = np.load(fname)
      num_slices = kspace.shape[0]
      self.examples += [(fname, slice) for slice in range(num_slices)] #文件+切片标号

  def __len__(self):
    return len(self.examples)
  
  def __getitem__(self, index):
    fname, slice_num = self.examples[index]
    data = np.load(fname)
    data_kspace = data[slice_num]
    data_kspace = torch.from_numpy(data_kspace)
    return torch.complex(data_kspace[:, :, 0], data_kspace[:, :, 1])



root = r"E:/MRI/data/Train_part1/e13992s4_P08704.7.npy"
dataset = SliceData(root)

import matplotlib.pyplot as plt

test_data = dataset[60]
test_image = torch.fft.ifft2(test_data, norm="backward")
print(test_image.shape)
plt.figure()
plt.imshow(np.abs(test_image.numpy()), cmap='gray')
plt.show()

